# Generated by Django 3.2.7 on 2021-11-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecko',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gecko',
            name='description',
            field=models.TextField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='gecko',
            name='name',
            field=models.CharField(default='No Name', max_length=50),
        ),
        migrations.AddField(
            model_name='gecko',
            name='species',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
