# Generated by Django 3.2.7 on 2021-11-03 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211102_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(choices=[('B', 'Beetles'), ('C', 'Crickets'), ('M', 'Mealworms'), ('S', 'Shed skin'), ('W', 'Waxworms')], default='C', max_length=1)),
                ('date', models.DateField()),
                ('gecko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.gecko')),
            ],
        ),
    ]
