# Generated by Django 3.2.7 on 2021-11-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_snack'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('heated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='snack',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='snack',
            name='date',
            field=models.DateField(verbose_name='Date fed'),
        ),
    ]
