# Generated by Django 3.2.7 on 2021-11-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211103_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecko',
            name='tank_items',
            field=models.ManyToManyField(to='main_app.TankItem'),
        ),
    ]
